# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ac20badab6b6d83e7aad4985c2f973f10f5a3bf12bc028bc1d49857ebae8a10758fb2da47387b0ea8cda8933f6a592108445a40690f53831342d02d845a7e21

test:
  secret_key_base: 9528eb3a69f830b25c7ed66a53b11b735ce1434c2a5c5570d7a76a0e0db0e5019800bdb45301a294ca083d3b365cff3e82b52add2fcfc1325776f9d5e0e960c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
